[versions]
version-name = "4.0.0-alpha.1"
android-versionCode = "1000"
android-compileSdk = "36"
android-minSdk = "28"
android-targetSdk = "36"

agp = "9.1.0"
androidx-activity-compose = "1.12.4"
androidx-appcompat = "1.7.1"
androidx-camera = "1.5.3"
androidx-datastore = "1.2.0"
androidx-paging3 = "3.4.1"
androidx-room = "2.8.4"
androidx-test-core = "1.7.0"
androidx-test-ext = "1.3.0"
androidx-test-runner = "1.7.0"
calvin-reorderable = "3.0.0"
coil = "3.4.0"
compose-material-icons-extended = "1.7.3"
compose-multiplatform = "1.10.2"
compose-multiplatform-lifecycle = "2.10.0-beta01"
compose-multiplatform-material3 = "1.11.0-alpha03"
compose-multiplatform-navigation-event = "1.0.1"
compose-multiplatform-navigation3 = "1.0.0-alpha06"
google-accompanist-permissions = "0.37.3"
google-zxing = "3.5.4"
koin = "4.1.1"
konform = "0.11.1"
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization-json = "1.10.0"
ksp = "2.3.4"
ktor = "3.4.1"
materialkolor = "4.1.1"
requery-sqlite-android = "3.49.0"
skydoves-colorpicker-compose = "1.1.3"
touchlab-kermit = "2.1.0"
valentinilk-shimmer = "1.3.3"
vinceglb-filekit = "0.13.0"

[libraries]
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidx-camera" }
androidx-datastore-preferencesCore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging3" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging3" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
calvin-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "calvin-reorderable" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-networkKtor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material-iconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons-extended" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-multiplatform-material3" }
compose-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "compose-multiplatform-navigation3" }
compose-navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "compose-multiplatform-navigation-event" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-ui-toolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
google-accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "google-accompanist-permissions" }
google-zxing-core = { module = "com.google.zxing:core", version.ref = "google-zxing" }
insert-koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
insert-koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
insert-koin-composeViewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
jetbrains-androidx-lifecycle-viewmodelNavigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "compose-multiplatform-lifecycle" }
konform = { module = "io.konform:konform", version.ref = "konform" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-clientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-clientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-clientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialkolor" }
requery-sqliteAndroid = { module = "com.github.requery:sqlite-android", version.ref = "requery-sqlite-android" }
skydoves-colorpickerCompose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "skydoves-colorpicker-compose" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "touchlab-kermit" }
valentinilk-shimmer-composeShimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "valentinilk-shimmer" }
vinceglb-filekitCoil = { module = "io.github.vinceglb:filekit-coil", version.ref = "vinceglb-filekit" }
vinceglb-filekitCore = { module = "io.github.vinceglb:filekit-core", version.ref = "vinceglb-filekit" }
vinceglb-filekitDialogsCompose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "vinceglb-filekit" }

[bundles]
androidx-android-ui = [
    "androidx-activityCompose",
    "androidx-appcompat"
]
androidx-test = [
    "androidx-test-core",
    "androidx-test-coreKtx",
    "androidx-test-ext-junit",
    "androidx-test-runner"
]
camera = [
    "androidx-camera-camera2",
    "androidx-camera-lifecycle",
    "androidx-camera-view"
]
coil = [
    "coil-compose",
    "coil-networkKtor3"
]
compose-core = [
    "compose-components-resources",
    "compose-foundation",
    "compose-material-iconsExtended",
    "compose-material3",
    "compose-runtime",
    "compose-ui",
    "compose-ui-toolingPreview"
]
compose-navigation = [
    "compose-navigation3-ui",
    "compose-navigationevent-compose",
    "jetbrains-androidx-lifecycle-viewmodelNavigation3"
]
filekit = [
    "vinceglb-filekitCoil",
    "vinceglb-filekitCore",
    "vinceglb-filekitDialogsCompose"
]
koin-compose = [
    "insert-koin-compose",
    "insert-koin-composeViewmodel"
]
kotlinx = [
    "kotlinx-datetime",
    "kotlinx-serializationJson"
]
ktor = [
    "ktor-clientContentNegotiation",
    "ktor-clientCore",
    "ktor-serializationKotlinxJson"
]
paging = [
    "androidx-paging-common",
    "androidx-paging-compose"
]
room = [
    "androidx-room-paging",
    "androidx-room-runtime"
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidxRoom = { id = "androidx.room", version.ref = "androidx-room" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
