name: Database Suggestion
description: Suggest a new external food database or data source.
title: "[Database Suggestion]: "
labels: [ "enhancement", "database", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new data source! Please provide the required information below.
  - type: input
    id: database-url
    attributes:
      label: Link to the database or API
      description: Provide the URL to the data source, web page, or API documentation.
      placeholder: https://world.openfoodfacts.org
    validations:
      required: true
  - type: textarea
    id: usage-terms
    attributes:
      label: Does the license or terms of use allow integration?
      description: Check and summarize whether this data source can legally be used in the app.
      placeholder: e.g., "Open license for commercial use", "Requires attribution", or "https://world.openfoodfacts.org/terms-of-use"
    validations:
      required: true
