name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: [ "enhancement", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! Please fill out the details below.
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: Provide a clear and concise description of the feature.
      placeholder: Describe the feature in detail.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: What problem does this feature solve?
      description: Explain how this feature will improve the project or address a specific issue.
      placeholder: Describe the problem or scenario.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered any alternatives?
      description: If applicable, share any alternative solutions you've thought about.
      placeholder: List alternative approaches, if any.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or ideas that might help.
      placeholder: Provide extra details or references.
