-keep,allowoptimization enum com.maksimowiczm.foodyou.core.feature.addfood.data.model.Meal
-keep,allowobfuscation,allowoptimization class com.maksimowiczm.foodyou.core.feature.product.network.openfoodfacts.model.** { *; }
