package com.maksimowiczm.foodyou.feature.importexport.domain.csv

fun csvHeader(): String = ProductEntityField.entries.joinToString(",") { it.name.lowercase() }

internal fun csvHeaderFields(): List<String> =
    ProductEntityField.entries.map { it.name.lowercase() }

internal enum class ProductEntityField {
    NAME,
    BRAND,
    BARCODE,
    PROTEINS,
    CARBOHYDRATES,
    FATS,
    CALORIES,
    SATURATED_FATS,
    MONOUNSATURATED_FATS,
    POLYUNSATURATED_FATS,
    OMEGA3,
    OMEGA6,
    SUGARS,
    SALT,
    FIBER,
    CHOLESTEROL_MILLI,
    CAFFEINE_MILLI,
    VITAMIN_A_MICRO,
    VITAMIN_B1_MILLI,
    VITAMIN_B2_MILLI,
    VITAMIN_B3_MILLI,
    VITAMIN_B5_MILLI,
    VITAMIN_B6_MILLI,
    VITAMIN_B7_MICRO,
    VITAMIN_B9_MICRO,
    VITAMIN_B12_MICRO,
    VITAMIN_C_MILLI,
    VITAMIN_D_MICRO,
    VITAMIN_E_MILLI,
    VITAMIN_K_MICRO,
    MANGANESE_MILLI,
    MAGNESIUM_MILLI,
    POTASSIUM_MILLI,
    CALCIUM_MILLI,
    COPPER_MILLI,
    ZINC_MILLI,
    SODIUM_MILLI,
    IRON_MILLI,
    PHOSPHORUS_MILLI,
    SELENIUM_MICRO,
    IODINE_MICRO,
    CHROMIUM_MICRO,
    PACKAGE_WEIGHT,
    SERVING_WEIGHT,
    IS_LIQUID,
    NOTE
}
