package com.maksimowiczm.foodyou.core.model

enum class NutritionFactsField {
    Energy,
    Proteins,
    Carbohydrates,
    Sugars,
    Fats,
    SaturatedFats,
    MonounsaturatedFats,
    PolyunsaturatedFats,
    Omega3,
    Omega6,
    Salt,
    Fiber,
    Cholesterol,
    Caffeine,
    VitaminA,
    VitaminB1,
    VitaminB2,
    VitaminB3,
    VitaminB5,
    VitaminB6,
    VitaminB7,
    VitaminB9,
    VitaminB12,
    VitaminC,
    VitaminD,
    VitaminE,
    VitaminK,
    Manganese,
    Magnesium,
    Potassium,
    Calcium,
    Copper,
    Zinc,
    Sodium,
    Iron,
    Phosphorus,
    Selenium,
    Iodine,
    Chromium;

    companion object
}
