package com.maksimowiczm.foodyou.common.infrastructure.food

import com.maksimowiczm.foodyou.common.domain.food.NutrientValue.Companion.toNutrientValue
import com.maksimowiczm.foodyou.common.domain.food.NutritionFacts
import com.maksimowiczm.foodyou.common.domain.grams
import com.maksimowiczm.foodyou.common.domain.kilocalories

class NutrientsMapper {
    fun toNutritionFats(entity: NutrientsEntity): NutritionFacts =
        NutritionFacts.requireAll(
            proteins = entity.proteins?.grams.toNutrientValue(),
            carbohydrates = entity.carbohydrates?.grams.toNutrientValue(),
            energy = entity.energy?.kilocalories.toNutrientValue(),
            fats = entity.fats?.grams.toNutrientValue(),
            saturatedFats = entity.saturatedFats?.grams.toNutrientValue(),
            transFats = entity.transFats?.grams.toNutrientValue(),
            monounsaturatedFats = entity.monounsaturatedFats?.grams.toNutrientValue(),
            polyunsaturatedFats = entity.polyunsaturatedFats?.grams.toNutrientValue(),
            omega3 = entity.omega3?.grams.toNutrientValue(),
            omega6 = entity.omega6?.grams.toNutrientValue(),
            sugars = entity.sugars?.grams.toNutrientValue(),
            addedSugars = entity.addedSugars?.grams.toNutrientValue(),
            dietaryFiber = entity.dietaryFiber?.grams.toNutrientValue(),
            solubleFiber = entity.solubleFiber?.grams.toNutrientValue(),
            insolubleFiber = entity.insolubleFiber?.grams.toNutrientValue(),
            salt = entity.salt?.grams.toNutrientValue(),
            cholesterol = entity.cholesterol?.grams.toNutrientValue(),
            caffeine = entity.caffeine?.grams.toNutrientValue(),
            vitaminA = entity.vitaminA?.grams.toNutrientValue(),
            vitaminB1 = entity.vitaminB1?.grams.toNutrientValue(),
            vitaminB2 = entity.vitaminB2?.grams.toNutrientValue(),
            vitaminB3 = entity.vitaminB3?.grams.toNutrientValue(),
            vitaminB5 = entity.vitaminB5?.grams.toNutrientValue(),
            vitaminB6 = entity.vitaminB6?.grams.toNutrientValue(),
            vitaminB7 = entity.vitaminB7?.grams.toNutrientValue(),
            vitaminB9 = entity.vitaminB9?.grams.toNutrientValue(),
            vitaminB12 = entity.vitaminB12?.grams.toNutrientValue(),
            vitaminC = entity.vitaminC?.grams.toNutrientValue(),
            vitaminD = entity.vitaminD?.grams.toNutrientValue(),
            vitaminE = entity.vitaminE?.grams.toNutrientValue(),
            vitaminK = entity.vitaminK?.grams.toNutrientValue(),
            manganese = entity.manganese?.grams.toNutrientValue(),
            magnesium = entity.magnesium?.grams.toNutrientValue(),
            potassium = entity.potassium?.grams.toNutrientValue(),
            calcium = entity.calcium?.grams.toNutrientValue(),
            copper = entity.copper?.grams.toNutrientValue(),
            zinc = entity.zinc?.grams.toNutrientValue(),
            sodium = entity.sodium?.grams.toNutrientValue(),
            iron = entity.iron?.grams.toNutrientValue(),
            phosphorus = entity.phosphorus?.grams.toNutrientValue(),
            selenium = entity.selenium?.grams.toNutrientValue(),
            iodine = entity.iodine?.grams.toNutrientValue(),
            chromium = entity.chromium?.grams.toNutrientValue(),
        )

    fun toNutrientsEntity(nutrients: NutritionFacts): NutrientsEntity =
        NutrientsEntity(
            proteins = nutrients.proteins.value?.grams,
            carbohydrates = nutrients.carbohydrates.value?.grams,
            energy = nutrients.energy.value?.kilocalories,
            fats = nutrients.fats.value?.grams,
            saturatedFats = nutrients.saturatedFats.value?.grams,
            transFats = nutrients.transFats.value?.grams,
            monounsaturatedFats = nutrients.monounsaturatedFats.value?.grams,
            polyunsaturatedFats = nutrients.polyunsaturatedFats.value?.grams,
            omega3 = nutrients.omega3.value?.grams,
            omega6 = nutrients.omega6.value?.grams,
            sugars = nutrients.sugars.value?.grams,
            addedSugars = nutrients.addedSugars.value?.grams,
            dietaryFiber = nutrients.dietaryFiber.value?.grams,
            solubleFiber = nutrients.solubleFiber.value?.grams,
            insolubleFiber = nutrients.insolubleFiber.value?.grams,
            salt = nutrients.salt.value?.grams,
            cholesterol = nutrients.cholesterol.value?.grams,
            caffeine = nutrients.caffeine.value?.grams,
            vitaminA = nutrients.vitaminA.value?.grams,
            vitaminB1 = nutrients.vitaminB1.value?.grams,
            vitaminB2 = nutrients.vitaminB2.value?.grams,
            vitaminB3 = nutrients.vitaminB3.value?.grams,
            vitaminB5 = nutrients.vitaminB5.value?.grams,
            vitaminB6 = nutrients.vitaminB6.value?.grams,
            vitaminB7 = nutrients.vitaminB7.value?.grams,
            vitaminB9 = nutrients.vitaminB9.value?.grams,
            vitaminB12 = nutrients.vitaminB12.value?.grams,
            vitaminC = nutrients.vitaminC.value?.grams,
            vitaminD = nutrients.vitaminD.value?.grams,
            vitaminE = nutrients.vitaminE.value?.grams,
            vitaminK = nutrients.vitaminK.value?.grams,
            manganese = nutrients.manganese.value?.grams,
            magnesium = nutrients.magnesium.value?.grams,
            potassium = nutrients.potassium.value?.grams,
            calcium = nutrients.calcium.value?.grams,
            copper = nutrients.copper.value?.grams,
            zinc = nutrients.zinc.value?.grams,
            sodium = nutrients.sodium.value?.grams,
            iron = nutrients.iron.value?.grams,
            phosphorus = nutrients.phosphorus.value?.grams,
            selenium = nutrients.selenium.value?.grams,
            iodine = nutrients.iodine.value?.grams,
            chromium = nutrients.chromium.value?.grams,
        )
}
