name: Release open source APK

on:
  workflow_dispatch:
    inputs:
      chosen-runner:
        required: true
        type: choice
        options:
          - self-hosted
          - ubuntu-latest

jobs:
  release-opensource:
    runs-on: "${{ inputs.chosen-runner }}"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build apk release
        run: ./gradlew --no-daemon assembleOpensourceRelease

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/opensource/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apks
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error
          retention-days: 14
