name: Validate Meals XML

on:
  push:
    paths:
      - 'app/src/opensource/res/xml*/meals.xml'
      - 'app/src/testOpensource/res/xml/meals-schema.xsd'
      - 'app/src/testOpensource/res/xml/test-meals.bash'
      - '.github/workflows/validate-meals.yml'
  pull_request:
    paths:
      - 'app/src/opensource/res/xml*/meals.xml'
      - 'app/src/testOpensource/res/xml/meals-schema.xsd'
      - 'app/src/testOpensource/res/xml/test-meals.bash'
      - '.github/workflows/validate-meals.yml'

jobs:
  validate-meals:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Validate meals.xml
        run: |
          ./app/src/testOpensource/res/xml/test-meals.bash
