name: Validate Meals

on:
  push:
    paths:
      - 'core/src/commonMain/composeResources/files/meals*'
      - 'dev/test-meals-localization.bash'
      - '.github/workflows/validate-meals.yml'
  pull_request:
    paths:
      - 'core/src/commonMain/composeResources/files/meals*'
      - 'dev/test-meals-localization.bash'
      - '.github/workflows/validate-meals.yml'

jobs:
  validate-meals:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Validate meals.json
        run: |
          ./dev/test-meals-localization.bash
